import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {
  // Test users removed - real users are created automatically via Clerk authentication

  // Seed assessment questions
  const assessmentQuestions = [
    // Beginner questions
    {
      question: 'What is a variable in programming?',
      type: 'multiple_choice',
      options: ['A container that stores data', 'A function that performs calculations', 'A loop that repeats code', 'A condition that checks values'],
      correctAnswer: 'A container that stores data',
      category: 'syntax',
      difficulty: 'beginner',
      language: null,
      explanation: 'A variable is a named container that stores data values that can be used and modified throughout a program.',
    },
    {
      question: 'What does the following code do?\n\nfor (let i = 0; i < 5; i++) {\n  console.log(i);\n}',
      type: 'conceptual',
      correctAnswer: 'Prints numbers 0 through 4',
      category: 'logic',
      difficulty: 'beginner',
      language: 'javascript',
      explanation: 'This is a for loop that starts at 0, continues while i is less than 5, and increments i by 1 each iteration. It prints 0, 1, 2, 3, 4.',
    },
    {
      question: 'What is the purpose of a function?',
      type: 'multiple_choice',
      options: ['To store data', 'To organize and reuse code', 'To create variables', 'To print output'],
      correctAnswer: 'To organize and reuse code',
      category: 'syntax',
      difficulty: 'beginner',
      language: null,
      explanation: 'Functions allow you to organize code into reusable blocks that can be called multiple times.',
    },
    // Intermediate questions
    {
      question: 'What is the time complexity of binary search?',
      type: 'multiple_choice',
      options: ['O(n)', 'O(log n)', 'O(n²)', 'O(1)'],
      correctAnswer: 'O(log n)',
      category: 'algorithms',
      difficulty: 'intermediate',
      language: null,
      explanation: 'Binary search has O(log n) time complexity because it eliminates half of the search space in each iteration.',
    },
    {
      question: 'What is the difference between == and === in JavaScript?',
      type: 'conceptual',
      correctAnswer: '== compares values with type coercion, === compares values and types strictly',
      category: 'syntax',
      difficulty: 'intermediate',
      language: 'javascript',
      explanation: '== performs type coercion before comparison, while === checks both value and type without coercion.',
    },
    {
      question: 'What is a closure in programming?',
      type: 'multiple_choice',
      options: ['A function that has access to variables in its outer scope', 'A way to close a program', 'A type of loop', 'A data structure'],
      correctAnswer: 'A function that has access to variables in its outer scope',
      category: 'syntax',
      difficulty: 'intermediate',
      language: null,
      explanation: 'A closure is a function that retains access to variables from its outer (enclosing) scope even after the outer function has finished executing.',
    },
    // Advanced questions
    {
      question: 'Explain the difference between stack and queue data structures.',
      type: 'conceptual',
      correctAnswer: 'Stack is LIFO (Last In First Out), Queue is FIFO (First In First Out)',
      category: 'data_structures',
      difficulty: 'advanced',
      language: null,
      explanation: 'Stack uses LIFO principle (like a stack of plates), while Queue uses FIFO principle (like a line of people).',
    },
    {
      question: 'What is memoization and when would you use it?',
      type: 'conceptual',
      correctAnswer: 'Memoization is caching function results to avoid redundant calculations, used for optimization',
      category: 'algorithms',
      difficulty: 'advanced',
      language: null,
      explanation: 'Memoization stores the results of expensive function calls and returns the cached result when the same inputs occur again, improving performance.',
    },
    // More beginner questions
    {
      question: 'What is an array?',
      type: 'multiple_choice',
      options: ['A collection of elements stored in contiguous memory', 'A single value', 'A function', 'A loop'],
      correctAnswer: 'A collection of elements stored in contiguous memory',
      category: 'data_structures',
      difficulty: 'beginner',
      language: null,
      explanation: 'An array is a data structure that stores a collection of elements, typically of the same type, in contiguous memory locations.',
    },
    {
      question: 'What does the if statement do?',
      type: 'multiple_choice',
      options: ['Repeats code', 'Executes code conditionally', 'Stores data', 'Defines a function'],
      correctAnswer: 'Executes code conditionally',
      category: 'logic',
      difficulty: 'beginner',
      language: null,
      explanation: 'An if statement allows you to execute code only when a certain condition is true.',
    },
    {
      question: 'What is a loop used for?',
      type: 'multiple_choice',
      options: ['Storing data', 'Repeating code multiple times', 'Defining variables', 'Printing output'],
      correctAnswer: 'Repeating code multiple times',
      category: 'logic',
      difficulty: 'beginner',
      language: null,
      explanation: 'Loops allow you to execute a block of code repeatedly until a certain condition is met.',
    },
    // More intermediate questions
    {
      question: 'What is recursion?',
      type: 'multiple_choice',
      options: ['A function that calls itself', 'A type of loop', 'A data structure', 'A variable'],
      correctAnswer: 'A function that calls itself',
      category: 'algorithms',
      difficulty: 'intermediate',
      language: null,
      explanation: 'Recursion is a programming technique where a function calls itself to solve a problem by breaking it down into smaller subproblems.',
    },
    {
      question: 'What is the difference between a list and a tuple in Python?',
      type: 'conceptual',
      correctAnswer: 'Lists are mutable, tuples are immutable',
      category: 'data_structures',
      difficulty: 'intermediate',
      language: 'python',
      explanation: 'Lists can be modified after creation (mutable), while tuples cannot be changed once created (immutable).',
    },
    {
      question: 'What is object-oriented programming (OOP)?',
      type: 'multiple_choice',
      options: ['A programming paradigm based on objects', 'A type of loop', 'A data structure', 'A function'],
      correctAnswer: 'A programming paradigm based on objects',
      category: 'syntax',
      difficulty: 'intermediate',
      language: null,
      explanation: 'OOP is a programming paradigm that organizes code into objects, which contain both data (attributes) and code (methods).',
    },
    // More advanced questions
    {
      question: 'What is the difference between pass-by-value and pass-by-reference?',
      type: 'conceptual',
      correctAnswer: 'Pass-by-value copies the value, pass-by-reference passes a reference to the original',
      category: 'syntax',
      difficulty: 'advanced',
      language: null,
      explanation: 'Pass-by-value creates a copy of the variable, while pass-by-reference passes a reference to the original variable, allowing modifications.',
    },
    {
      question: 'What is a hash table and what is its average time complexity for lookups?',
      type: 'conceptual',
      correctAnswer: 'A data structure that maps keys to values, O(1) average time complexity',
      category: 'data_structures',
      difficulty: 'advanced',
      language: null,
      explanation: 'A hash table uses a hash function to map keys to array indices, providing average O(1) time complexity for insertions, deletions, and lookups.',
    },
    // Python-specific questions
    {
      question: 'What is a list comprehension in Python?',
      type: 'conceptual',
      correctAnswer: 'A concise way to create lists based on existing lists',
      category: 'syntax',
      difficulty: 'intermediate',
      language: 'python',
      explanation: 'List comprehensions provide a concise way to create lists by applying an expression to each item in an iterable, optionally with filtering.',
    },
    // JavaScript-specific questions
    {
      question: 'What is the difference between let, const, and var in JavaScript?',
      type: 'conceptual',
      correctAnswer: 'let and const are block-scoped, var is function-scoped; const cannot be reassigned',
      category: 'syntax',
      difficulty: 'intermediate',
      language: 'javascript',
      explanation: 'let and const are block-scoped and cannot be hoisted, while var is function-scoped and can be hoisted. const also prevents reassignment.',
    },
    {
      question: 'What is the event loop in JavaScript?',
      type: 'conceptual',
      correctAnswer: 'A mechanism that handles asynchronous operations by continuously checking the call stack and callback queue',
      category: 'syntax',
      difficulty: 'advanced',
      language: 'javascript',
      explanation: 'The event loop is JavaScript\'s mechanism for handling asynchronous operations, managing the call stack, callback queue, and microtask queue.',
    },
    // Additional beginner questions
    {
      question: 'What is a data type?',
      type: 'multiple_choice',
      options: ['A category of data values', 'A variable name', 'A function', 'A loop'],
      correctAnswer: 'A category of data values',
      category: 'syntax',
      difficulty: 'beginner',
      language: null,
      explanation: 'A data type defines the kind of value a variable can hold, such as numbers, strings, or booleans.',
    },
    {
      question: 'What is a string?',
      type: 'multiple_choice',
      options: ['A sequence of characters', 'A number', 'A boolean value', 'A function'],
      correctAnswer: 'A sequence of characters',
      category: 'syntax',
      difficulty: 'beginner',
      language: null,
      explanation: 'A string is a data type that represents a sequence of characters, typically enclosed in quotes.',
    },
    {
      question: 'What is an integer?',
      type: 'multiple_choice',
      options: ['A whole number', 'A decimal number', 'A string', 'A boolean'],
      correctAnswer: 'A whole number',
      category: 'syntax',
      difficulty: 'beginner',
      language: null,
      explanation: 'An integer is a whole number without decimal points, such as 1, 42, or -10.',
    },
    {
      question: 'What does the while loop do?',
      type: 'multiple_choice',
      options: ['Repeats code while a condition is true', 'Stores data', 'Defines a function', 'Prints output'],
      correctAnswer: 'Repeats code while a condition is true',
      category: 'logic',
      difficulty: 'beginner',
      language: null,
      explanation: 'A while loop repeatedly executes a block of code as long as a specified condition remains true.',
    },
    {
      question: 'What is a boolean?',
      type: 'multiple_choice',
      options: ['A true or false value', 'A number', 'A string', 'A function'],
      correctAnswer: 'A true or false value',
      category: 'syntax',
      difficulty: 'beginner',
      language: null,
      explanation: 'A boolean is a data type that can only have two values: true or false.',
    },
    // Additional intermediate questions
    {
      question: 'What is a class in object-oriented programming?',
      type: 'multiple_choice',
      options: ['A blueprint for creating objects', 'A variable', 'A function', 'A loop'],
      correctAnswer: 'A blueprint for creating objects',
      category: 'syntax',
      difficulty: 'intermediate',
      language: null,
      explanation: 'A class is a template or blueprint that defines the properties and methods that objects of that class will have.',
    },
    {
      question: 'What is inheritance in OOP?',
      type: 'conceptual',
      correctAnswer: 'A mechanism where a class can inherit properties and methods from another class',
      category: 'syntax',
      difficulty: 'intermediate',
      language: null,
      explanation: 'Inheritance allows a class to inherit attributes and methods from a parent class, promoting code reuse.',
    },
    {
      question: 'What is polymorphism?',
      type: 'conceptual',
      correctAnswer: 'The ability of objects to take on multiple forms or have multiple behaviors',
      category: 'syntax',
      difficulty: 'intermediate',
      language: null,
      explanation: 'Polymorphism allows objects of different types to be treated as objects of a common base type.',
    },
    {
      question: 'What is the time complexity of linear search?',
      type: 'multiple_choice',
      options: ['O(n)', 'O(log n)', 'O(n²)', 'O(1)'],
      correctAnswer: 'O(n)',
      category: 'algorithms',
      difficulty: 'intermediate',
      language: null,
      explanation: 'Linear search has O(n) time complexity because it may need to check every element in the worst case.',
    },
    {
      question: 'What is a linked list?',
      type: 'multiple_choice',
      options: ['A data structure where elements are linked using pointers', 'An array', 'A function', 'A loop'],
      correctAnswer: 'A data structure where elements are linked using pointers',
      category: 'data_structures',
      difficulty: 'intermediate',
      language: null,
      explanation: 'A linked list is a linear data structure where each element points to the next element in the sequence.',
    },
    {
      question: 'What is a binary tree?',
      type: 'conceptual',
      correctAnswer: 'A tree data structure where each node has at most two children',
      category: 'data_structures',
      difficulty: 'intermediate',
      language: null,
      explanation: 'A binary tree is a hierarchical data structure where each node has at most two child nodes.',
    },
    // Additional advanced questions
    {
      question: 'What is dynamic programming?',
      type: 'conceptual',
      correctAnswer: 'A method for solving complex problems by breaking them down into simpler subproblems and storing results',
      category: 'algorithms',
      difficulty: 'advanced',
      language: null,
      explanation: 'Dynamic programming solves problems by combining solutions to overlapping subproblems, often using memoization.',
    },
    {
      question: 'What is a graph data structure?',
      type: 'conceptual',
      correctAnswer: 'A collection of nodes connected by edges',
      category: 'data_structures',
      difficulty: 'advanced',
      language: null,
      explanation: 'A graph is a data structure consisting of vertices (nodes) connected by edges, representing relationships.',
    },
    {
      question: 'What is the difference between BFS and DFS?',
      type: 'conceptual',
      correctAnswer: 'BFS explores level by level using a queue, DFS explores as deep as possible using a stack or recursion',
      category: 'algorithms',
      difficulty: 'advanced',
      language: null,
      explanation: 'BFS (Breadth-First Search) explores neighbors first, while DFS (Depth-First Search) explores as far as possible before backtracking.',
    },
    {
      question: 'What is a heap data structure?',
      type: 'conceptual',
      correctAnswer: 'A complete binary tree that satisfies the heap property (parent nodes are greater/lesser than children)',
      category: 'data_structures',
      difficulty: 'advanced',
      language: null,
      explanation: 'A heap is a specialized tree-based data structure that maintains a specific ordering property.',
    },
    {
      question: 'What is the time complexity of quicksort in the average case?',
      type: 'multiple_choice',
      options: ['O(n log n)', 'O(n²)', 'O(n)', 'O(log n)'],
      correctAnswer: 'O(n log n)',
      category: 'algorithms',
      difficulty: 'advanced',
      language: null,
      explanation: 'Quicksort has O(n log n) average time complexity, making it one of the most efficient sorting algorithms.',
    },
    // TypeScript-specific questions
    {
      question: 'What is a type annotation in TypeScript?',
      type: 'conceptual',
      correctAnswer: 'Explicitly specifying the type of a variable, parameter, or return value',
      category: 'syntax',
      difficulty: 'intermediate',
      language: 'typescript',
      explanation: 'Type annotations in TypeScript allow you to explicitly declare the type of variables, making code more type-safe.',
    },
    {
      question: 'What is an interface in TypeScript?',
      type: 'conceptual',
      correctAnswer: 'A contract that defines the structure of an object',
      category: 'syntax',
      difficulty: 'intermediate',
      language: 'typescript',
      explanation: 'An interface in TypeScript defines the shape of an object, specifying what properties and methods it must have.',
    },
    // Python-specific questions
    {
      question: 'What is a dictionary in Python?',
      type: 'multiple_choice',
      options: ['A key-value pair data structure', 'A list', 'A tuple', 'A string'],
      correctAnswer: 'A key-value pair data structure',
      category: 'data_structures',
      difficulty: 'intermediate',
      language: 'python',
      explanation: 'A dictionary in Python is an unordered collection of key-value pairs, similar to a hash map.',
    },
    {
      question: 'What is a generator in Python?',
      type: 'conceptual',
      correctAnswer: 'A function that returns an iterator and can be paused and resumed',
      category: 'syntax',
      difficulty: 'advanced',
      language: 'python',
      explanation: 'A generator is a special type of function that uses yield to produce values one at a time, saving memory.',
    },
    // Java-specific questions
    {
      question: 'What is the difference between == and .equals() in Java?',
      type: 'conceptual',
      correctAnswer: '== compares references, .equals() compares values',
      category: 'syntax',
      difficulty: 'intermediate',
      language: 'java',
      explanation: '== checks if two references point to the same object, while .equals() compares the actual values.',
    },
    // C++ specific questions
    {
      question: 'What is a pointer in C++?',
      type: 'conceptual',
      correctAnswer: 'A variable that stores the memory address of another variable',
      category: 'syntax',
      difficulty: 'intermediate',
      language: 'cpp',
      explanation: 'A pointer is a variable that holds the memory address of another variable, allowing indirect access to data.',
    },
  ]

  for (const question of assessmentQuestions) {
    const questionId = `q-${question.question.substring(0, 30).replace(/\s/g, '-').toLowerCase()}`
    await prisma.assessmentQuestion.upsert({
      where: { id: questionId },
      update: {},
      create: {
        id: questionId,
        question: question.question,
        type: question.type as any,
        options: question.options ? question.options as any : null,
        correctAnswer: question.correctAnswer,
        category: question.category,
        difficulty: question.difficulty,
        language: question.language,
        explanation: question.explanation || null,
      },
    })
  }

  // Seed programming tasks
  const programmingTasks = [
    // JavaScript tasks
    {
      title: 'Find Maximum in Array',
      description: 'Write a function that finds and returns the maximum value in an array of numbers.',
      language: 'javascript',
      difficulty: 'beginner',
      category: 'algorithms',
      starterCode: 'function findMax(arr) {\n    // Your code here\n}',
      hints: [
        'Initialize a variable to track the maximum',
        'Loop through the array',
        'Compare each element with the current maximum'
      ],
      solution: 'function findMax(arr) {\n    let max = arr[0];\n    for (let i = 1; i < arr.length; i++) {\n        if (arr[i] > max) max = arr[i];\n    }\n    return max;\n}',
    },
    {
      title: 'Reverse a String',
      description: 'Write a function that takes a string as input and returns the string reversed. For example, "hello" should become "olleh".',
      language: 'javascript',
      difficulty: 'beginner',
      category: 'algorithms',
      starterCode: 'function reverseString(str) {\n    // Your code here\n}',
      hints: [
        'You can convert string to array, reverse it, and join back',
        'Or use a loop to build a new string',
        'Consider using split() and reverse() methods'
      ],
      solution: 'function reverseString(str) {\n    return str.split("").reverse().join("");\n}',
    },
    {
      title: 'Count Vowels',
      description: 'Write a function that counts the number of vowels (a, e, i, o, u) in a given string.',
      language: 'javascript',
      difficulty: 'beginner',
      category: 'algorithms',
      starterCode: 'function countVowels(str) {\n    // Your code here\n}',
      hints: [
        'Convert string to lowercase for case-insensitive matching',
        'Loop through each character',
        'Check if character is a vowel'
      ],
      solution: 'function countVowels(str) {\n    const vowels = "aeiou";\n    let count = 0;\n    for (let char of str.toLowerCase()) {\n        if (vowels.includes(char)) count++;\n    }\n    return count;\n}',
    },
    {
      title: 'Binary Search',
      description: 'Implement binary search to find a target value in a sorted array. Return the index if found, -1 otherwise.',
      language: 'javascript',
      difficulty: 'intermediate',
      category: 'algorithms',
      starterCode: 'function binarySearch(arr, target) {\n    // Your code here\n}',
      hints: [
        'Use two pointers: left and right',
        'Calculate the middle index',
        'Compare target with middle element and adjust pointers'
      ],
      solution: 'function binarySearch(arr, target) {\n    let left = 0, right = arr.length - 1;\n    while (left <= right) {\n        let mid = Math.floor((left + right) / 2);\n        if (arr[mid] === target) return mid;\n        if (arr[mid] < target) left = mid + 1;\n        else right = mid - 1;\n    }\n    return -1;\n}',
    },
    {
      title: 'Check Palindrome',
      description: 'Write a function that checks if a string is a palindrome (reads the same forwards and backwards).',
      language: 'javascript',
      difficulty: 'intermediate',
      category: 'algorithms',
      starterCode: 'function isPalindrome(str) {\n    // Your code here\n}',
      hints: [
        'Remove spaces and convert to lowercase',
        'Compare the string with its reverse',
        'Or use two pointers approach'
      ],
      solution: 'function isPalindrome(str) {\n    const cleaned = str.toLowerCase().replace(/\\s/g, "");\n    return cleaned === cleaned.split("").reverse().join("");\n}',
    },
    {
      title: 'Two Sum',
      description: 'Given an array of integers and a target sum, find two numbers that add up to the target. Return their indices.',
      language: 'javascript',
      difficulty: 'intermediate',
      category: 'algorithms',
      starterCode: 'function twoSum(nums, target) {\n    // Your code here\n}',
      hints: [
        'Use a hash map to store seen numbers',
        'For each number, check if complement exists',
        'Return indices when complement is found'
      ],
      solution: 'function twoSum(nums, target) {\n    const map = {};\n    for (let i = 0; i < nums.length; i++) {\n        const complement = target - nums[i];\n        if (map[complement] !== undefined) {\n            return [map[complement], i];\n        }\n        map[nums[i]] = i;\n    }\n    return [];\n}',
    },
    {
      title: 'Merge Sorted Arrays',
      description: 'Merge two sorted arrays into one sorted array without using built-in sort methods.',
      language: 'javascript',
      difficulty: 'advanced',
      category: 'algorithms',
      starterCode: 'function mergeSortedArrays(arr1, arr2) {\n    // Your code here\n}',
      hints: [
        'Use two pointers, one for each array',
        'Compare elements and add smaller one to result',
        'Handle remaining elements after one array is exhausted'
      ],
      solution: 'function mergeSortedArrays(arr1, arr2) {\n    let i = 0, j = 0, result = [];\n    while (i < arr1.length && j < arr2.length) {\n        if (arr1[i] < arr2[j]) {\n            result.push(arr1[i++]);\n        } else {\n            result.push(arr2[j++]);\n        }\n    }\n    return result.concat(arr1.slice(i)).concat(arr2.slice(j));\n}',
    },
    // TypeScript tasks
    {
      title: 'Find Maximum in Array',
      description: 'Write a function that finds and returns the maximum value in an array of numbers.',
      language: 'typescript',
      difficulty: 'beginner',
      category: 'algorithms',
      starterCode: 'function findMax(arr: number[]): number {\n    // Your code here\n}',
      hints: [
        'Initialize a variable to track the maximum',
        'Loop through the array',
        'Compare each element with the current maximum'
      ],
      solution: 'function findMax(arr: number[]): number {\n    let max = arr[0];\n    for (let i = 1; i < arr.length; i++) {\n        if (arr[i] > max) max = arr[i];\n    }\n    return max;\n}',
    },
    {
      title: 'Reverse a String',
      description: 'Write a function that takes a string as input and returns the string reversed. For example, "hello" should become "olleh".',
      language: 'typescript',
      difficulty: 'beginner',
      category: 'algorithms',
      starterCode: 'function reverseString(str: string): string {\n    // Your code here\n}',
      hints: [
        'You can convert string to array, reverse it, and join back',
        'Or use a loop to build a new string',
        'Consider using split() and reverse() methods'
      ],
      solution: 'function reverseString(str: string): string {\n    return str.split("").reverse().join("");\n}',
    },
    {
      title: 'Count Vowels',
      description: 'Write a function that counts the number of vowels (a, e, i, o, u) in a given string.',
      language: 'typescript',
      difficulty: 'beginner',
      category: 'algorithms',
      starterCode: 'function countVowels(str: string): number {\n    // Your code here\n}',
      hints: [
        'Convert string to lowercase for case-insensitive matching',
        'Loop through each character',
        'Check if character is a vowel'
      ],
      solution: 'function countVowels(str: string): number {\n    const vowels = "aeiou";\n    let count = 0;\n    for (let char of str.toLowerCase()) {\n        if (vowels.includes(char)) count++;\n    }\n    return count;\n}',
    },
    {
      title: 'Binary Search',
      description: 'Implement binary search to find a target value in a sorted array. Return the index if found, -1 otherwise.',
      language: 'typescript',
      difficulty: 'intermediate',
      category: 'algorithms',
      starterCode: 'function binarySearch(arr: number[], target: number): number {\n    // Your code here\n}',
      hints: [
        'Use two pointers: left and right',
        'Calculate the middle index',
        'Compare target with middle element and adjust pointers'
      ],
      solution: 'function binarySearch(arr: number[], target: number): number {\n    let left = 0, right = arr.length - 1;\n    while (left <= right) {\n        let mid = Math.floor((left + right) / 2);\n        if (arr[mid] === target) return mid;\n        if (arr[mid] < target) left = mid + 1;\n        else right = mid - 1;\n    }\n    return -1;\n}',
    },
    {
      title: 'Check Palindrome',
      description: 'Write a function that checks if a string is a palindrome (reads the same forwards and backwards).',
      language: 'typescript',
      difficulty: 'intermediate',
      category: 'algorithms',
      starterCode: 'function isPalindrome(str: string): boolean {\n    // Your code here\n}',
      hints: [
        'Remove spaces and convert to lowercase',
        'Compare the string with its reverse',
        'Or use two pointers approach'
      ],
      solution: 'function isPalindrome(str: string): boolean {\n    const cleaned = str.toLowerCase().replace(/\\s/g, "");\n    return cleaned === cleaned.split("").reverse().join("");\n}',
    },
    {
      title: 'Two Sum',
      description: 'Given an array of integers and a target sum, find two numbers that add up to the target. Return their indices.',
      language: 'typescript',
      difficulty: 'intermediate',
      category: 'algorithms',
      starterCode: 'function twoSum(nums: number[], target: number): number[] {\n    // Your code here\n}',
      hints: [
        'Use a hash map to store seen numbers',
        'For each number, check if complement exists',
        'Return indices when complement is found'
      ],
      solution: 'function twoSum(nums: number[], target: number): number[] {\n    const map: { [key: number]: number } = {};\n    for (let i = 0; i < nums.length; i++) {\n        const complement = target - nums[i];\n        if (map[complement] !== undefined) {\n            return [map[complement], i];\n        }\n        map[nums[i]] = i;\n    }\n    return [];\n}',
    },
    {
      title: 'Merge Sorted Arrays',
      description: 'Merge two sorted arrays into one sorted array without using built-in sort methods.',
      language: 'typescript',
      difficulty: 'advanced',
      category: 'algorithms',
      starterCode: 'function mergeSortedArrays(arr1: number[], arr2: number[]): number[] {\n    // Your code here\n}',
      hints: [
        'Use two pointers, one for each array',
        'Compare elements and add smaller one to result',
        'Handle remaining elements after one array is exhausted'
      ],
      solution: 'function mergeSortedArrays(arr1: number[], arr2: number[]): number[] {\n    let i = 0, j = 0, result: number[] = [];\n    while (i < arr1.length && j < arr2.length) {\n        if (arr1[i] < arr2[j]) {\n            result.push(arr1[i++]);\n        } else {\n            result.push(arr2[j++]);\n        }\n    }\n    return result.concat(arr1.slice(i)).concat(arr2.slice(j));\n}',
    },
    // Python tasks
    {
      title: 'Reverse a String',
      description: 'Write a function that takes a string as input and returns the string reversed. For example, "hello" should become "olleh".',
      language: 'python',
      difficulty: 'beginner',
      category: 'algorithms',
      starterCode: 'def reverse_string(s):\n    # Your code here\n    pass',
      hints: [
        'Think about how to iterate through the string',
        'You can use slicing in Python',
        'Or build a new string character by character'
      ],
      solution: 'def reverse_string(s):\n    return s[::-1]',
    },
    {
      title: 'Check Palindrome',
      description: 'Write a function that checks if a string is a palindrome (reads the same forwards and backwards).',
      language: 'python',
      difficulty: 'intermediate',
      category: 'algorithms',
      starterCode: 'def is_palindrome(s):\n    # Your code here\n    pass',
      hints: [
        'Remove spaces and convert to lowercase',
        'Compare the string with its reverse',
        'Or use two pointers approach'
      ],
      solution: 'def is_palindrome(s):\n    s = s.lower().replace(" ", "")\n    return s == s[::-1]',
    },
    {
      title: 'Find Maximum in Array',
      description: 'Write a function that finds and returns the maximum value in an array of numbers.',
      language: 'python',
      difficulty: 'beginner',
      category: 'algorithms',
      starterCode: 'def find_max(arr):\n    # Your code here\n    pass',
      hints: [
        'Initialize a variable to track the maximum',
        'Loop through the array',
        'Compare each element with the current maximum'
      ],
      solution: 'def find_max(arr):\n    max_val = arr[0]\n    for num in arr[1:]:\n        if num > max_val:\n            max_val = num\n    return max_val',
    },
    {
      title: 'Count Vowels',
      description: 'Write a function that counts the number of vowels (a, e, i, o, u) in a given string.',
      language: 'python',
      difficulty: 'beginner',
      category: 'algorithms',
      starterCode: 'def count_vowels(s):\n    # Your code here\n    pass',
      hints: [
        'Convert string to lowercase for case-insensitive matching',
        'Loop through each character',
        'Check if character is a vowel'
      ],
      solution: 'def count_vowels(s):\n    vowels = "aeiou"\n    return sum(1 for char in s.lower() if char in vowels)',
    },
    {
      title: 'Binary Search',
      description: 'Implement binary search to find a target value in a sorted array. Return the index if found, -1 otherwise.',
      language: 'python',
      difficulty: 'intermediate',
      category: 'algorithms',
      starterCode: 'def binary_search(arr, target):\n    # Your code here\n    pass',
      hints: [
        'Use two pointers: left and right',
        'Calculate the middle index',
        'Compare target with middle element and adjust pointers'
      ],
      solution: 'def binary_search(arr, target):\n    left, right = 0, len(arr) - 1\n    while left <= right:\n        mid = (left + right) // 2\n        if arr[mid] == target:\n            return mid\n        elif arr[mid] < target:\n            left = mid + 1\n        else:\n            right = mid - 1\n    return -1',
    },
    {
      title: 'Two Sum',
      description: 'Given an array of integers and a target sum, find two numbers that add up to the target. Return their indices.',
      language: 'python',
      difficulty: 'intermediate',
      category: 'algorithms',
      starterCode: 'def two_sum(nums, target):\n    # Your code here\n    pass',
      hints: [
        'Use a dictionary to store seen numbers',
        'For each number, check if complement exists',
        'Return indices when complement is found'
      ],
      solution: 'def two_sum(nums, target):\n    seen = {}\n    for i, num in enumerate(nums):\n        complement = target - num\n        if complement in seen:\n            return [seen[complement], i]\n        seen[num] = i\n    return []',
    },
    {
      title: 'Merge Sorted Arrays',
      description: 'Merge two sorted arrays into one sorted array without using built-in sort methods.',
      language: 'python',
      difficulty: 'advanced',
      category: 'algorithms',
      starterCode: 'def merge_sorted_arrays(arr1, arr2):\n    # Your code here\n    pass',
      hints: [
        'Use two pointers, one for each array',
        'Compare elements and add smaller one to result',
        'Handle remaining elements after one array is exhausted'
      ],
      solution: 'def merge_sorted_arrays(arr1, arr2):\n    i, j = 0, 0\n    result = []\n    while i < len(arr1) and j < len(arr2):\n        if arr1[i] < arr2[j]:\n            result.append(arr1[i])\n            i += 1\n        else:\n            result.append(arr2[j])\n            j += 1\n    result.extend(arr1[i:])\n    result.extend(arr2[j:])\n    return result',
    },
    // Java tasks
    {
      title: 'Find Maximum in Array',
      description: 'Write a method that finds and returns the maximum value in an array of integers.',
      language: 'java',
      difficulty: 'beginner',
      category: 'algorithms',
      starterCode: 'public static int findMax(int[] arr) {\n    // Your code here\n    return 0;\n}',
      hints: ['Initialize a variable to track the maximum', 'Loop through the array', 'Compare each element with the current maximum'],
      solution: 'public static int findMax(int[] arr) {\n    int max = arr[0];\n    for (int i = 1; i < arr.length; i++) {\n        if (arr[i] > max) max = arr[i];\n    }\n    return max;\n}',
    },
    {
      title: 'Reverse a String',
      description: 'Write a method that takes a string as input and returns the string reversed.',
      language: 'java',
      difficulty: 'beginner',
      category: 'algorithms',
      starterCode: 'public static String reverseString(String str) {\n    // Your code here\n    return "";\n}',
      hints: ['Use StringBuilder for efficient string manipulation', 'Loop through characters in reverse', 'Or use built-in methods'],
      solution: 'public static String reverseString(String str) {\n    return new StringBuilder(str).reverse().toString();\n}',
    },
    {
      title: 'Check Palindrome',
      description: 'Write a method that checks if a string is a palindrome.',
      language: 'java',
      difficulty: 'intermediate',
      category: 'algorithms',
      starterCode: 'public static boolean isPalindrome(String str) {\n    // Your code here\n    return false;\n}',
      hints: ['Remove spaces and convert to lowercase', 'Compare characters from both ends', 'Use two pointers'],
      solution: 'public static boolean isPalindrome(String str) {\n    String cleaned = str.toLowerCase().replaceAll("\\\\s", "");\n    return cleaned.equals(new StringBuilder(cleaned).reverse().toString());\n}',
    },
    {
      title: 'Binary Search',
      description: 'Implement binary search to find a target value in a sorted array.',
      language: 'java',
      difficulty: 'intermediate',
      category: 'algorithms',
      starterCode: 'public static int binarySearch(int[] arr, int target) {\n    // Your code here\n    return -1;\n}',
      hints: ['Use two pointers: left and right', 'Calculate the middle index', 'Compare target with middle element'],
      solution: 'public static int binarySearch(int[] arr, int target) {\n    int left = 0, right = arr.length - 1;\n    while (left <= right) {\n        int mid = left + (right - left) / 2;\n        if (arr[mid] == target) return mid;\n        if (arr[mid] < target) left = mid + 1;\n        else right = mid - 1;\n    }\n    return -1;\n}',
    },
    {
      title: 'Two Sum',
      description: 'Given an array of integers and a target sum, find two numbers that add up to the target.',
      language: 'java',
      difficulty: 'intermediate',
      category: 'algorithms',
      starterCode: 'public static int[] twoSum(int[] nums, int target) {\n    // Your code here\n    return new int[0];\n}',
      hints: ['Use a HashMap to store seen numbers', 'For each number, check if complement exists', 'Return indices when complement is found'],
      solution: 'public static int[] twoSum(int[] nums, int target) {\n    Map<Integer, Integer> map = new HashMap<>();\n    for (int i = 0; i < nums.length; i++) {\n        int complement = target - nums[i];\n        if (map.containsKey(complement)) {\n            return new int[]{map.get(complement), i};\n        }\n        map.put(nums[i], i);\n    }\n    return new int[0];\n}',
    },
    {
      title: 'Merge Sorted Arrays',
      description: 'Merge two sorted arrays into one sorted array without using built-in sort methods.',
      language: 'java',
      difficulty: 'advanced',
      category: 'algorithms',
      starterCode: 'public static int[] mergeSortedArrays(int[] arr1, int[] arr2) {\n    // Your code here\n    return new int[0];\n}',
      hints: ['Use two pointers, one for each array', 'Compare elements and add smaller one to result', 'Handle remaining elements after one array is exhausted'],
      solution: 'public static int[] mergeSortedArrays(int[] arr1, int[] arr2) {\n    int i = 0, j = 0, k = 0;\n    int[] result = new int[arr1.length + arr2.length];\n    while (i < arr1.length && j < arr2.length) {\n        if (arr1[i] < arr2[j]) result[k++] = arr1[i++];\n        else result[k++] = arr2[j++];\n    }\n    while (i < arr1.length) result[k++] = arr1[i++];\n    while (j < arr2.length) result[k++] = arr2[j++];\n    return result;\n}',
    },
    {
      title: 'Count Vowels',
      description: 'Write a method that counts the number of vowels (a, e, i, o, u) in a given string.',
      language: 'java',
      difficulty: 'beginner',
      category: 'algorithms',
      starterCode: 'public static int countVowels(String str) {\n    // Your code here\n    return 0;\n}',
      hints: ['Convert string to lowercase for case-insensitive matching', 'Loop through each character', 'Check if character is a vowel'],
      solution: 'public static int countVowels(String str) {\n    String vowels = "aeiou";\n    int count = 0;\n    for (char c : str.toLowerCase().toCharArray()) {\n        if (vowels.indexOf(c) != -1) count++;\n    }\n    return count;\n}',
    },
    // C++ tasks
    {
      title: 'Find Maximum in Array',
      description: 'Write a function that finds and returns the maximum value in an array of integers.',
      language: 'cpp',
      difficulty: 'beginner',
      category: 'algorithms',
      starterCode: 'int findMax(int arr[], int size) {\n    // Your code here\n    return 0;\n}',
      hints: ['Initialize a variable to track the maximum', 'Loop through the array', 'Compare each element with the current maximum'],
      solution: 'int findMax(int arr[], int size) {\n    int max = arr[0];\n    for (int i = 1; i < size; i++) {\n        if (arr[i] > max) max = arr[i];\n    }\n    return max;\n}',
    },
    {
      title: 'Reverse a String',
      description: 'Write a function that takes a string and returns it reversed.',
      language: 'cpp',
      difficulty: 'beginner',
      category: 'algorithms',
      starterCode: 'string reverseString(string str) {\n    // Your code here\n    return "";\n}',
      hints: ['Use two pointers approach', 'Swap characters from both ends', 'Or use built-in reverse function'],
      solution: 'string reverseString(string str) {\n    reverse(str.begin(), str.end());\n    return str;\n}',
    },
    {
      title: 'Binary Search',
      description: 'Implement binary search to find a target value in a sorted array.',
      language: 'cpp',
      difficulty: 'intermediate',
      category: 'algorithms',
      starterCode: 'int binarySearch(int arr[], int size, int target) {\n    // Your code here\n    return -1;\n}',
      hints: ['Use two pointers: left and right', 'Calculate the middle index', 'Compare target with middle element'],
      solution: 'int binarySearch(int arr[], int size, int target) {\n    int left = 0, right = size - 1;\n    while (left <= right) {\n        int mid = left + (right - left) / 2;\n        if (arr[mid] == target) return mid;\n        if (arr[mid] < target) left = mid + 1;\n        else right = mid - 1;\n    }\n    return -1;\n}',
    },
    {
      title: 'Two Sum',
      description: 'Given an array of integers and a target sum, find two numbers that add up to the target.',
      language: 'cpp',
      difficulty: 'intermediate',
      category: 'algorithms',
      starterCode: 'vector<int> twoSum(vector<int>& nums, int target) {\n    // Your code here\n    return {};\n}',
      hints: ['Use an unordered_map to store seen numbers', 'For each number, check if complement exists', 'Return indices when complement is found'],
      solution: 'vector<int> twoSum(vector<int>& nums, int target) {\n    unordered_map<int, int> map;\n    for (int i = 0; i < nums.size(); i++) {\n        int complement = target - nums[i];\n        if (map.find(complement) != map.end()) {\n            return {map[complement], i};\n        }\n        map[nums[i]] = i;\n    }\n    return {};\n}',
    },
    {
      title: 'Merge Sorted Arrays',
      description: 'Merge two sorted arrays into one sorted array without using built-in sort methods.',
      language: 'cpp',
      difficulty: 'advanced',
      category: 'algorithms',
      starterCode: 'vector<int> mergeSortedArrays(vector<int>& arr1, vector<int>& arr2) {\n    // Your code here\n    return {};\n}',
      hints: ['Use two pointers, one for each array', 'Compare elements and add smaller one to result', 'Handle remaining elements after one array is exhausted'],
      solution: 'vector<int> mergeSortedArrays(vector<int>& arr1, vector<int>& arr2) {\n    vector<int> result;\n    int i = 0, j = 0;\n    while (i < arr1.size() && j < arr2.size()) {\n        if (arr1[i] < arr2[j]) result.push_back(arr1[i++]);\n        else result.push_back(arr2[j++]);\n    }\n    while (i < arr1.size()) result.push_back(arr1[i++]);\n    while (j < arr2.size()) result.push_back(arr2[j++]);\n    return result;\n}',
    },
    {
      title: 'Count Vowels',
      description: 'Write a function that counts the number of vowels (a, e, i, o, u) in a given string.',
      language: 'cpp',
      difficulty: 'beginner',
      category: 'algorithms',
      starterCode: 'int countVowels(string str) {\n    // Your code here\n    return 0;\n}',
      hints: ['Convert string to lowercase for case-insensitive matching', 'Loop through each character', 'Check if character is a vowel'],
      solution: 'int countVowels(string str) {\n    string vowels = "aeiou";\n    int count = 0;\n    for (char c : str) {\n        if (vowels.find(tolower(c)) != string::npos) count++;\n    }\n    return count;\n}',
    },
    // C# tasks
    {
      title: 'Find Maximum in Array',
      description: 'Write a method that finds and returns the maximum value in an array of integers.',
      language: 'csharp',
      difficulty: 'beginner',
      category: 'algorithms',
      starterCode: 'public static int FindMax(int[] arr) {\n    // Your code here\n    return 0;\n}',
      hints: ['Initialize a variable to track the maximum', 'Loop through the array', 'Compare each element with the current maximum'],
      solution: 'public static int FindMax(int[] arr) {\n    int max = arr[0];\n    for (int i = 1; i < arr.Length; i++) {\n        if (arr[i] > max) max = arr[i];\n    }\n    return max;\n}',
    },
    {
      title: 'Reverse a String',
      description: 'Write a method that takes a string and returns it reversed.',
      language: 'csharp',
      difficulty: 'beginner',
      category: 'algorithms',
      starterCode: 'public static string ReverseString(string str) {\n    // Your code here\n    return "";\n}',
      hints: ['Convert string to char array', 'Use Array.Reverse or manual reversal', 'Return new string'],
      solution: 'public static string ReverseString(string str) {\n    char[] chars = str.ToCharArray();\n    Array.Reverse(chars);\n    return new string(chars);\n}',
    },
    {
      title: 'Check Palindrome',
      description: 'Write a method that checks if a string is a palindrome.',
      language: 'csharp',
      difficulty: 'intermediate',
      category: 'algorithms',
      starterCode: 'public static bool IsPalindrome(string str) {\n    // Your code here\n    return false;\n}',
      hints: ['Remove spaces and convert to lowercase', 'Compare characters from both ends', 'Use two pointers'],
      solution: 'public static bool IsPalindrome(string str) {\n    string cleaned = str.ToLower().Replace(" ", "");\n    char[] chars = cleaned.ToCharArray();\n    Array.Reverse(chars);\n    return cleaned == new string(chars);\n}',
    },
    {
      title: 'Binary Search',
      description: 'Implement binary search to find a target value in a sorted array.',
      language: 'csharp',
      difficulty: 'intermediate',
      category: 'algorithms',
      starterCode: 'public static int BinarySearch(int[] arr, int target) {\n    // Your code here\n    return -1;\n}',
      hints: ['Use two pointers: left and right', 'Calculate the middle index', 'Compare target with middle element'],
      solution: 'public static int BinarySearch(int[] arr, int target) {\n    int left = 0, right = arr.Length - 1;\n    while (left <= right) {\n        int mid = left + (right - left) / 2;\n        if (arr[mid] == target) return mid;\n        if (arr[mid] < target) left = mid + 1;\n        else right = mid - 1;\n    }\n    return -1;\n}',
    },
    {
      title: 'Two Sum',
      description: 'Given an array of integers and a target sum, find two numbers that add up to the target.',
      language: 'csharp',
      difficulty: 'intermediate',
      category: 'algorithms',
      starterCode: 'public static int[] TwoSum(int[] nums, int target) {\n    // Your code here\n    return new int[0];\n}',
      hints: ['Use a Dictionary to store seen numbers', 'For each number, check if complement exists', 'Return indices when complement is found'],
      solution: 'public static int[] TwoSum(int[] nums, int target) {\n    Dictionary<int, int> map = new Dictionary<int, int>();\n    for (int i = 0; i < nums.Length; i++) {\n        int complement = target - nums[i];\n        if (map.ContainsKey(complement)) {\n            return new int[] { map[complement], i };\n        }\n        map[nums[i]] = i;\n    }\n    return new int[0];\n}',
    },
    {
      title: 'Merge Sorted Arrays',
      description: 'Merge two sorted arrays into one sorted array without using built-in sort methods.',
      language: 'csharp',
      difficulty: 'advanced',
      category: 'algorithms',
      starterCode: 'public static int[] MergeSortedArrays(int[] arr1, int[] arr2) {\n    // Your code here\n    return new int[0];\n}',
      hints: ['Use two pointers, one for each array', 'Compare elements and add smaller one to result', 'Handle remaining elements after one array is exhausted'],
      solution: 'public static int[] MergeSortedArrays(int[] arr1, int[] arr2) {\n    int i = 0, j = 0, k = 0;\n    int[] result = new int[arr1.Length + arr2.Length];\n    while (i < arr1.Length && j < arr2.Length) {\n        if (arr1[i] < arr2[j]) result[k++] = arr1[i++];\n        else result[k++] = arr2[j++];\n    }\n    while (i < arr1.Length) result[k++] = arr1[i++];\n    while (j < arr2.Length) result[k++] = arr2[j++];\n    return result;\n}',
    },
    {
      title: 'Count Vowels',
      description: 'Write a method that counts the number of vowels (a, e, i, o, u) in a given string.',
      language: 'csharp',
      difficulty: 'beginner',
      category: 'algorithms',
      starterCode: 'public static int CountVowels(string str) {\n    // Your code here\n    return 0;\n}',
      hints: ['Convert string to lowercase for case-insensitive matching', 'Loop through each character', 'Check if character is a vowel'],
      solution: 'public static int CountVowels(string str) {\n    string vowels = "aeiou";\n    int count = 0;\n    foreach (char c in str.ToLower()) {\n        if (vowels.Contains(c)) count++;\n    }\n    return count;\n}',
    },
    // Rust tasks
    {
      title: 'Find Maximum in Array',
      description: 'Write a function that finds and returns the maximum value in a vector of integers.',
      language: 'rust',
      difficulty: 'beginner',
      category: 'algorithms',
      starterCode: 'fn find_max(arr: &[i32]) -> i32 {\n    // Your code here\n    0\n}',
      hints: ['Use iterator methods', 'Or use a loop with mutable variable', 'Consider using max() method'],
      solution: 'fn find_max(arr: &[i32]) -> i32 {\n    *arr.iter().max().unwrap()\n}',
    },
    {
      title: 'Reverse a String',
      description: 'Write a function that takes a string and returns it reversed.',
      language: 'rust',
      difficulty: 'beginner',
      category: 'algorithms',
      starterCode: 'fn reverse_string(s: &str) -> String {\n    // Your code here\n    String::new()\n}',
      hints: ['Convert to chars iterator', 'Reverse the iterator', 'Collect into String'],
      solution: 'fn reverse_string(s: &str) -> String {\n    s.chars().rev().collect()\n}',
    },
    {
      title: 'Binary Search',
      description: 'Implement binary search to find a target value in a sorted array.',
      language: 'rust',
      difficulty: 'intermediate',
      category: 'algorithms',
      starterCode: 'fn binary_search(arr: &[i32], target: i32) -> Option<usize> {\n    // Your code here\n    None\n}',
      hints: ['Use two pointers: left and right', 'Calculate the middle index', 'Compare target with middle element'],
      solution: 'fn binary_search(arr: &[i32], target: i32) -> Option<usize> {\n    let mut left = 0;\n    let mut right = arr.len();\n    while left < right {\n        let mid = left + (right - left) / 2;\n        if arr[mid] == target { return Some(mid); }\n        if arr[mid] < target { left = mid + 1; }\n        else { right = mid; }\n    }\n    None\n}',
    },
    {
      title: 'Two Sum',
      description: 'Given an array of integers and a target sum, find two numbers that add up to the target.',
      language: 'rust',
      difficulty: 'intermediate',
      category: 'algorithms',
      starterCode: 'fn two_sum(nums: &[i32], target: i32) -> Option<(usize, usize)> {\n    // Your code here\n    None\n}',
      hints: ['Use a HashMap to store seen numbers', 'For each number, check if complement exists', 'Return indices when complement is found'],
      solution: 'use std::collections::HashMap;\nfn two_sum(nums: &[i32], target: i32) -> Option<(usize, usize)> {\n    let mut map = HashMap::new();\n    for (i, &num) in nums.iter().enumerate() {\n        let complement = target - num;\n        if let Some(&j) = map.get(&complement) {\n            return Some((j, i));\n        }\n        map.insert(num, i);\n    }\n    None\n}',
    },
    {
      title: 'Merge Sorted Arrays',
      description: 'Merge two sorted arrays into one sorted array without using built-in sort methods.',
      language: 'rust',
      difficulty: 'advanced',
      category: 'algorithms',
      starterCode: 'fn merge_sorted_arrays(arr1: &[i32], arr2: &[i32]) -> Vec<i32> {\n    // Your code here\n    Vec::new()\n}',
      hints: ['Use two pointers, one for each array', 'Compare elements and add smaller one to result', 'Handle remaining elements after one array is exhausted'],
      solution: 'fn merge_sorted_arrays(arr1: &[i32], arr2: &[i32]) -> Vec<i32> {\n    let mut result = Vec::new();\n    let mut i = 0;\n    let mut j = 0;\n    while i < arr1.len() && j < arr2.len() {\n        if arr1[i] < arr2[j] {\n            result.push(arr1[i]);\n            i += 1;\n        } else {\n            result.push(arr2[j]);\n            j += 1;\n        }\n    }\n    result.extend_from_slice(&arr1[i..]);\n    result.extend_from_slice(&arr2[j..]);\n    result\n}',
    },
    {
      title: 'Count Vowels',
      description: 'Write a function that counts the number of vowels (a, e, i, o, u) in a given string.',
      language: 'rust',
      difficulty: 'beginner',
      category: 'algorithms',
      starterCode: 'fn count_vowels(s: &str) -> usize {\n    // Your code here\n    0\n}',
      hints: ['Convert string to lowercase for case-insensitive matching', 'Loop through each character', 'Check if character is a vowel'],
      solution: 'fn count_vowels(s: &str) -> usize {\n    let vowels = "aeiou";\n    s.to_lowercase().chars().filter(|c| vowels.contains(*c)).count()\n}',
    },
    // Go tasks
    {
      title: 'Find Maximum in Array',
      description: 'Write a function that finds and returns the maximum value in a slice of integers.',
      language: 'go',
      difficulty: 'beginner',
      category: 'algorithms',
      starterCode: 'func findMax(arr []int) int {\n    // Your code here\n    return 0\n}',
      hints: ['Initialize a variable to track the maximum', 'Loop through the slice', 'Compare each element'],
      solution: 'func findMax(arr []int) int {\n    max := arr[0]\n    for i := 1; i < len(arr); i++ {\n        if arr[i] > max {\n            max = arr[i]\n        }\n    }\n    return max\n}',
    },
    {
      title: 'Reverse a String',
      description: 'Write a function that takes a string and returns it reversed.',
      language: 'go',
      difficulty: 'beginner',
      category: 'algorithms',
      starterCode: 'func reverseString(s string) string {\n    // Your code here\n    return ""\n}',
      hints: ['Convert string to rune slice', 'Reverse the slice', 'Convert back to string'],
      solution: 'func reverseString(s string) string {\n    runes := []rune(s)\n    for i, j := 0, len(runes)-1; i < j; i, j = i+1, j-1 {\n        runes[i], runes[j] = runes[j], runes[i]\n    }\n    return string(runes)\n}',
    },
    {
      title: 'Binary Search',
      description: 'Implement binary search to find a target value in a sorted array.',
      language: 'go',
      difficulty: 'intermediate',
      category: 'algorithms',
      starterCode: 'func binarySearch(arr []int, target int) int {\n    // Your code here\n    return -1\n}',
      hints: ['Use two pointers: left and right', 'Calculate the middle index', 'Compare target with middle element'],
      solution: 'func binarySearch(arr []int, target int) int {\n    left, right := 0, len(arr)-1\n    for left <= right {\n        mid := left + (right-left)/2\n        if arr[mid] == target {\n            return mid\n        }\n        if arr[mid] < target {\n            left = mid + 1\n        } else {\n            right = mid - 1\n        }\n    }\n    return -1\n}',
    },
    {
      title: 'Two Sum',
      description: 'Given an array of integers and a target sum, find two numbers that add up to the target.',
      language: 'go',
      difficulty: 'intermediate',
      category: 'algorithms',
      starterCode: 'func twoSum(nums []int, target int) []int {\n    // Your code here\n    return []int{}\n}',
      hints: ['Use a map to store seen numbers', 'For each number, check if complement exists', 'Return indices when complement is found'],
      solution: 'func twoSum(nums []int, target int) []int {\n    m := make(map[int]int)\n    for i, num := range nums {\n        complement := target - num\n        if idx, ok := m[complement]; ok {\n            return []int{idx, i}\n        }\n        m[num] = i\n    }\n    return []int{}\n}',
    },
    {
      title: 'Merge Sorted Arrays',
      description: 'Merge two sorted arrays into one sorted array without using built-in sort methods.',
      language: 'go',
      difficulty: 'advanced',
      category: 'algorithms',
      starterCode: 'func mergeSortedArrays(arr1, arr2 []int) []int {\n    // Your code here\n    return []int{}\n}',
      hints: ['Use two pointers, one for each array', 'Compare elements and add smaller one to result', 'Handle remaining elements after one array is exhausted'],
      solution: 'func mergeSortedArrays(arr1, arr2 []int) []int {\n    result := make([]int, 0, len(arr1)+len(arr2))\n    i, j := 0, 0\n    for i < len(arr1) && j < len(arr2) {\n        if arr1[i] < arr2[j] {\n            result = append(result, arr1[i])\n            i++\n        } else {\n            result = append(result, arr2[j])\n            j++\n        }\n    }\n    result = append(result, arr1[i:]...)\n    result = append(result, arr2[j:]...)\n    return result\n}',
    },
    {
      title: 'Count Vowels',
      description: 'Write a function that counts the number of vowels (a, e, i, o, u) in a given string.',
      language: 'go',
      difficulty: 'beginner',
      category: 'algorithms',
      starterCode: 'func countVowels(s string) int {\n    // Your code here\n    return 0\n}',
      hints: ['Convert string to lowercase for case-insensitive matching', 'Loop through each character', 'Check if character is a vowel'],
      solution: 'func countVowels(s string) int {\n    vowels := "aeiou"\n    count := 0\n    for _, char := range strings.ToLower(s) {\n        if strings.ContainsRune(vowels, char) {\n            count++\n        }\n    }\n    return count\n}',
    },
    // Ruby tasks
    {
      title: 'Find Maximum in Array',
      description: 'Write a method that finds and returns the maximum value in an array of numbers.',
      language: 'ruby',
      difficulty: 'beginner',
      category: 'algorithms',
      starterCode: 'def find_max(arr)\n    # Your code here\nend',
      hints: ['Use the max method', 'Or iterate through the array', 'Compare each element'],
      solution: 'def find_max(arr)\n    arr.max\nend',
    },
    {
      title: 'Reverse a String',
      description: 'Write a method that takes a string and returns it reversed.',
      language: 'ruby',
      difficulty: 'beginner',
      category: 'algorithms',
      starterCode: 'def reverse_string(str)\n    # Your code here\nend',
      hints: ['Use the reverse method', 'Or build a new string character by character'],
      solution: 'def reverse_string(str)\n    str.reverse\nend',
    },
    {
      title: 'Binary Search',
      description: 'Implement binary search to find a target value in a sorted array.',
      language: 'ruby',
      difficulty: 'intermediate',
      category: 'algorithms',
      starterCode: 'def binary_search(arr, target)\n    # Your code here\n    -1\nend',
      hints: ['Use two pointers: left and right', 'Calculate the middle index', 'Compare target with middle element'],
      solution: 'def binary_search(arr, target)\n    left = 0\n    right = arr.length - 1\n    while left <= right\n        mid = left + (right - left) / 2\n        return mid if arr[mid] == target\n        if arr[mid] < target\n            left = mid + 1\n        else\n            right = mid - 1\n        end\n    end\n    -1\nend',
    },
    {
      title: 'Two Sum',
      description: 'Given an array of integers and a target sum, find two numbers that add up to the target.',
      language: 'ruby',
      difficulty: 'intermediate',
      category: 'algorithms',
      starterCode: 'def two_sum(nums, target)\n    # Your code here\n    []\nend',
      hints: ['Use a hash to store seen numbers', 'For each number, check if complement exists', 'Return indices when complement is found'],
      solution: 'def two_sum(nums, target)\n    seen = {}\n    nums.each_with_index do |num, i|\n        complement = target - num\n        return [seen[complement], i] if seen.key?(complement)\n        seen[num] = i\n    end\n    []\nend',
    },
    {
      title: 'Check Palindrome',
      description: 'Write a method that checks if a string is a palindrome.',
      language: 'ruby',
      difficulty: 'intermediate',
      category: 'algorithms',
      starterCode: 'def is_palindrome(str)\n    # Your code here\n    false\nend',
      hints: ['Remove spaces and convert to lowercase', 'Compare the string with its reverse'],
      solution: 'def is_palindrome(str)\n    cleaned = str.downcase.gsub(/\\s/, "")\n    cleaned == cleaned.reverse\nend',
    },
    {
      title: 'Merge Sorted Arrays',
      description: 'Merge two sorted arrays into one sorted array without using built-in sort methods.',
      language: 'ruby',
      difficulty: 'advanced',
      category: 'algorithms',
      starterCode: 'def merge_sorted_arrays(arr1, arr2)\n    # Your code here\n    []\nend',
      hints: ['Use two pointers, one for each array', 'Compare elements and add smaller one to result', 'Handle remaining elements after one array is exhausted'],
      solution: 'def merge_sorted_arrays(arr1, arr2)\n    result = []\n    i = j = 0\n    while i < arr1.length && j < arr2.length\n        if arr1[i] < arr2[j]\n            result << arr1[i]\n            i += 1\n        else\n            result << arr2[j]\n            j += 1\n        end\n    end\n    result + arr1[i..-1] + arr2[j..-1]\nend',
    },
    {
      title: 'Count Vowels',
      description: 'Write a method that counts the number of vowels (a, e, i, o, u) in a given string.',
      language: 'ruby',
      difficulty: 'beginner',
      category: 'algorithms',
      starterCode: 'def count_vowels(str)\n    # Your code here\n    0\nend',
      hints: ['Convert string to lowercase for case-insensitive matching', 'Count characters that are vowels'],
      solution: 'def count_vowels(str)\n    str.downcase.count("aeiou")\nend',
    },
    // PHP tasks
    {
      title: 'Find Maximum in Array',
      description: 'Write a function that finds and returns the maximum value in an array of numbers.',
      language: 'php',
      difficulty: 'beginner',
      category: 'algorithms',
      starterCode: 'function findMax($arr) {\n    // Your code here\n}',
      hints: ['Use max() function', 'Or loop through the array', 'Compare each element'],
      solution: 'function findMax($arr) {\n    return max($arr);\n}',
    },
    {
      title: 'Reverse a String',
      description: 'Write a function that takes a string and returns it reversed.',
      language: 'php',
      difficulty: 'beginner',
      category: 'algorithms',
      starterCode: 'function reverseString($str) {\n    // Your code here\n}',
      hints: ['Use strrev() function', 'Or build a new string character by character'],
      solution: 'function reverseString($str) {\n    return strrev($str);\n}',
    },
    {
      title: 'Binary Search',
      description: 'Implement binary search to find a target value in a sorted array.',
      language: 'php',
      difficulty: 'intermediate',
      category: 'algorithms',
      starterCode: 'function binarySearch($arr, $target) {\n    // Your code here\n    return -1;\n}',
      hints: ['Use two pointers: left and right', 'Calculate the middle index', 'Compare target with middle element'],
      solution: 'function binarySearch($arr, $target) {\n    $left = 0;\n    $right = count($arr) - 1;\n    while ($left <= $right) {\n        $mid = $left + intval(($right - $left) / 2);\n        if ($arr[$mid] == $target) return $mid;\n        if ($arr[$mid] < $target) $left = $mid + 1;\n        else $right = $mid - 1;\n    }\n    return -1;\n}',
    },
    {
      title: 'Two Sum',
      description: 'Given an array of integers and a target sum, find two numbers that add up to the target.',
      language: 'php',
      difficulty: 'intermediate',
      category: 'algorithms',
      starterCode: 'function twoSum($nums, $target) {\n    // Your code here\n    return [];\n}',
      hints: ['Use an associative array to store seen numbers', 'For each number, check if complement exists', 'Return indices when complement is found'],
      solution: 'function twoSum($nums, $target) {\n    $map = [];\n    for ($i = 0; $i < count($nums); $i++) {\n        $complement = $target - $nums[$i];\n        if (isset($map[$complement])) {\n            return [$map[$complement], $i];\n        }\n        $map[$nums[$i]] = $i;\n    }\n    return [];\n}',
    },
    {
      title: 'Check Palindrome',
      description: 'Write a function that checks if a string is a palindrome.',
      language: 'php',
      difficulty: 'intermediate',
      category: 'algorithms',
      starterCode: 'function isPalindrome($str) {\n    // Your code here\n    return false;\n}',
      hints: ['Remove spaces and convert to lowercase', 'Compare the string with its reverse'],
      solution: 'function isPalindrome($str) {\n    $cleaned = strtolower(str_replace(" ", "", $str));\n    return $cleaned == strrev($cleaned);\n}',
    },
    {
      title: 'Merge Sorted Arrays',
      description: 'Merge two sorted arrays into one sorted array without using built-in sort methods.',
      language: 'php',
      difficulty: 'advanced',
      category: 'algorithms',
      starterCode: 'function mergeSortedArrays($arr1, $arr2) {\n    // Your code here\n    return [];\n}',
      hints: ['Use two pointers, one for each array', 'Compare elements and add smaller one to result', 'Handle remaining elements after one array is exhausted'],
      solution: 'function mergeSortedArrays($arr1, $arr2) {\n    $result = [];\n    $i = $j = 0;\n    while ($i < count($arr1) && $j < count($arr2)) {\n        if ($arr1[$i] < $arr2[$j]) {\n            $result[] = $arr1[$i++];\n        } else {\n            $result[] = $arr2[$j++];\n        }\n    }\n    while ($i < count($arr1)) $result[] = $arr1[$i++];\n    while ($j < count($arr2)) $result[] = $arr2[$j++];\n    return $result;\n}',
    },
    {
      title: 'Count Vowels',
      description: 'Write a function that counts the number of vowels (a, e, i, o, u) in a given string.',
      language: 'php',
      difficulty: 'beginner',
      category: 'algorithms',
      starterCode: 'function countVowels($str) {\n    // Your code here\n    return 0;\n}',
      hints: ['Convert string to lowercase for case-insensitive matching', 'Count vowels using preg_match_all or str_split'],
      solution: 'function countVowels($str) {\n    return preg_match_all("/[aeiou]/i", $str);\n}',
    },
    // Swift tasks
    {
      title: 'Find Maximum in Array',
      description: 'Write a function that finds and returns the maximum value in an array of integers.',
      language: 'swift',
      difficulty: 'beginner',
      category: 'algorithms',
      starterCode: 'func findMax(_ arr: [Int]) -> Int {\n    // Your code here\n    return 0\n}',
      hints: ['Use max() method', 'Or iterate through the array', 'Compare each element'],
      solution: 'func findMax(_ arr: [Int]) -> Int {\n    return arr.max() ?? 0\n}',
    },
    {
      title: 'Reverse a String',
      description: 'Write a function that takes a string and returns it reversed.',
      language: 'swift',
      difficulty: 'beginner',
      category: 'algorithms',
      starterCode: 'func reverseString(_ str: String) -> String {\n    // Your code here\n    return ""\n}',
      hints: ['Use String(str.reversed())', 'Or build a new string character by character'],
      solution: 'func reverseString(_ str: String) -> String {\n    return String(str.reversed())\n}',
    },
    {
      title: 'Binary Search',
      description: 'Implement binary search to find a target value in a sorted array.',
      language: 'swift',
      difficulty: 'intermediate',
      category: 'algorithms',
      starterCode: 'func binarySearch(_ arr: [Int], _ target: Int) -> Int? {\n    // Your code here\n    return nil\n}',
      hints: ['Use two pointers: left and right', 'Calculate the middle index', 'Compare target with middle element'],
      solution: 'func binarySearch(_ arr: [Int], _ target: Int) -> Int? {\n    var left = 0\n    var right = arr.count - 1\n    while left <= right {\n        let mid = left + (right - left) / 2\n        if arr[mid] == target { return mid }\n        if arr[mid] < target { left = mid + 1 }\n        else { right = mid - 1 }\n    }\n    return nil\n}',
    },
    {
      title: 'Two Sum',
      description: 'Given an array of integers and a target sum, find two numbers that add up to the target.',
      language: 'swift',
      difficulty: 'intermediate',
      category: 'algorithms',
      starterCode: 'func twoSum(_ nums: [Int], _ target: Int) -> [Int] {\n    // Your code here\n    return []\n}',
      hints: ['Use a dictionary to store seen numbers', 'For each number, check if complement exists', 'Return indices when complement is found'],
      solution: 'func twoSum(_ nums: [Int], _ target: Int) -> [Int] {\n    var map: [Int: Int] = [:]\n    for (i, num) in nums.enumerated() {\n        let complement = target - num\n        if let idx = map[complement] {\n            return [idx, i]\n        }\n        map[num] = i\n    }\n    return []\n}',
    },
    {
      title: 'Check Palindrome',
      description: 'Write a function that checks if a string is a palindrome.',
      language: 'swift',
      difficulty: 'intermediate',
      category: 'algorithms',
      starterCode: 'func isPalindrome(_ str: String) -> Bool {\n    // Your code here\n    return false\n}',
      hints: ['Remove spaces and convert to lowercase', 'Compare the string with its reverse'],
      solution: 'func isPalindrome(_ str: String) -> Bool {\n    let cleaned = str.lowercased().replacingOccurrences(of: " ", with: "")\n    return cleaned == String(cleaned.reversed())\n}',
    },
    {
      title: 'Merge Sorted Arrays',
      description: 'Merge two sorted arrays into one sorted array without using built-in sort methods.',
      language: 'swift',
      difficulty: 'advanced',
      category: 'algorithms',
      starterCode: 'func mergeSortedArrays(_ arr1: [Int], _ arr2: [Int]) -> [Int] {\n    // Your code here\n    return []\n}',
      hints: ['Use two pointers, one for each array', 'Compare elements and add smaller one to result', 'Handle remaining elements after one array is exhausted'],
      solution: 'func mergeSortedArrays(_ arr1: [Int], _ arr2: [Int]) -> [Int] {\n    var result: [Int] = []\n    var i = 0, j = 0\n    while i < arr1.count && j < arr2.count {\n        if arr1[i] < arr2[j] {\n            result.append(arr1[i])\n            i += 1\n        } else {\n            result.append(arr2[j])\n            j += 1\n        }\n    }\n    result.append(contentsOf: arr1[i...])\n    result.append(contentsOf: arr2[j...])\n    return result\n}',
    },
    {
      title: 'Count Vowels',
      description: 'Write a function that counts the number of vowels (a, e, i, o, u) in a given string.',
      language: 'swift',
      difficulty: 'beginner',
      category: 'algorithms',
      starterCode: 'func countVowels(_ str: String) -> Int {\n    // Your code here\n    return 0\n}',
      hints: ['Convert string to lowercase for case-insensitive matching', 'Filter and count vowels'],
      solution: 'func countVowels(_ str: String) -> Int {\n    let vowels = "aeiou"\n    return str.lowercased().filter { vowels.contains($0) }.count\n}',
    },
    // Kotlin tasks
    {
      title: 'Find Maximum in Array',
      description: 'Write a function that finds and returns the maximum value in an array of integers.',
      language: 'kotlin',
      difficulty: 'beginner',
      category: 'algorithms',
      starterCode: 'fun findMax(arr: IntArray): Int {\n    // Your code here\n    return 0\n}',
      hints: ['Use maxOrNull() method', 'Or iterate through the array', 'Compare each element'],
      solution: 'fun findMax(arr: IntArray): Int {\n    return arr.maxOrNull() ?: 0\n}',
    },
    {
      title: 'Reverse a String',
      description: 'Write a function that takes a string and returns it reversed.',
      language: 'kotlin',
      difficulty: 'beginner',
      category: 'algorithms',
      starterCode: 'fun reverseString(str: String): String {\n    // Your code here\n    return ""\n}',
      hints: ['Use reversed() method', 'Or build a new string character by character'],
      solution: 'fun reverseString(str: String): String {\n    return str.reversed()\n}',
    },
    {
      title: 'Binary Search',
      description: 'Implement binary search to find a target value in a sorted array.',
      language: 'kotlin',
      difficulty: 'intermediate',
      category: 'algorithms',
      starterCode: 'fun binarySearch(arr: IntArray, target: Int): Int {\n    // Your code here\n    return -1\n}',
      hints: ['Use two pointers: left and right', 'Calculate the middle index', 'Compare target with middle element'],
      solution: 'fun binarySearch(arr: IntArray, target: Int): Int {\n    var left = 0\n    var right = arr.size - 1\n    while (left <= right) {\n        val mid = left + (right - left) / 2\n        when {\n            arr[mid] == target -> return mid\n            arr[mid] < target -> left = mid + 1\n            else -> right = mid - 1\n        }\n    }\n    return -1\n}',
    },
    {
      title: 'Two Sum',
      description: 'Given an array of integers and a target sum, find two numbers that add up to the target.',
      language: 'kotlin',
      difficulty: 'intermediate',
      category: 'algorithms',
      starterCode: 'fun twoSum(nums: IntArray, target: Int): IntArray {\n    // Your code here\n    return intArrayOf()\n}',
      hints: ['Use a map to store seen numbers', 'For each number, check if complement exists', 'Return indices when complement is found'],
      solution: 'fun twoSum(nums: IntArray, target: Int): IntArray {\n    val map = mutableMapOf<Int, Int>()\n    for (i in nums.indices) {\n        val complement = target - nums[i]\n        if (map.containsKey(complement)) {\n            return intArrayOf(map[complement]!!, i)\n        }\n        map[nums[i]] = i\n    }\n    return intArrayOf()\n}',
    },
    {
      title: 'Check Palindrome',
      description: 'Write a function that checks if a string is a palindrome.',
      language: 'kotlin',
      difficulty: 'intermediate',
      category: 'algorithms',
      starterCode: 'fun isPalindrome(str: String): Boolean {\n    // Your code here\n    return false\n}',
      hints: ['Remove spaces and convert to lowercase', 'Compare the string with its reverse'],
      solution: 'fun isPalindrome(str: String): Boolean {\n    val cleaned = str.lowercase().replace(" ", "")\n    return cleaned == cleaned.reversed()\n}',
    },
    {
      title: 'Merge Sorted Arrays',
      description: 'Merge two sorted arrays into one sorted array without using built-in sort methods.',
      language: 'kotlin',
      difficulty: 'advanced',
      category: 'algorithms',
      starterCode: 'fun mergeSortedArrays(arr1: IntArray, arr2: IntArray): IntArray {\n    // Your code here\n    return intArrayOf()\n}',
      hints: ['Use two pointers, one for each array', 'Compare elements and add smaller one to result', 'Handle remaining elements after one array is exhausted'],
      solution: 'fun mergeSortedArrays(arr1: IntArray, arr2: IntArray): IntArray {\n    val result = mutableListOf<Int>()\n    var i = 0\n    var j = 0\n    while (i < arr1.size && j < arr2.size) {\n        if (arr1[i] < arr2[j]) result.add(arr1[i++])\n        else result.add(arr2[j++])\n    }\n    while (i < arr1.size) result.add(arr1[i++])\n    while (j < arr2.size) result.add(arr2[j++])\n    return result.toIntArray()\n}',
    },
    {
      title: 'Count Vowels',
      description: 'Write a function that counts the number of vowels (a, e, i, o, u) in a given string.',
      language: 'kotlin',
      difficulty: 'beginner',
      category: 'algorithms',
      starterCode: 'fun countVowels(str: String): Int {\n    // Your code here\n    return 0\n}',
      hints: ['Convert string to lowercase for case-insensitive matching', 'Count vowels using filter'],
      solution: 'fun countVowels(str: String): Int {\n    val vowels = "aeiou"\n    return str.lowercase().count { it in vowels }\n}',
    },
    // Dart tasks
    {
      title: 'Find Maximum in Array',
      description: 'Write a function that finds and returns the maximum value in a list of integers.',
      language: 'dart',
      difficulty: 'beginner',
      category: 'algorithms',
      starterCode: 'int findMax(List<int> arr) {\n    // Your code here\n    return 0;\n}',
      hints: ['Use reduce method', 'Or iterate through the list', 'Compare each element'],
      solution: 'int findMax(List<int> arr) {\n    return arr.reduce((a, b) => a > b ? a : b);\n}',
    },
    {
      title: 'Reverse a String',
      description: 'Write a function that takes a string and returns it reversed.',
      language: 'dart',
      difficulty: 'beginner',
      category: 'algorithms',
      starterCode: 'String reverseString(String str) {\n    // Your code here\n    return "";\n}',
      hints: ['Split string into characters', 'Reverse the list', 'Join back'],
      solution: 'String reverseString(String str) {\n    return str.split("").reversed.join("");\n}',
    },
    {
      title: 'Binary Search',
      description: 'Implement binary search to find a target value in a sorted array.',
      language: 'dart',
      difficulty: 'intermediate',
      category: 'algorithms',
      starterCode: 'int binarySearch(List<int> arr, int target) {\n    // Your code here\n    return -1;\n}',
      hints: ['Use two pointers: left and right', 'Calculate the middle index', 'Compare target with middle element'],
      solution: 'int binarySearch(List<int> arr, int target) {\n    int left = 0, right = arr.length - 1;\n    while (left <= right) {\n        int mid = left + (right - left) ~/ 2;\n        if (arr[mid] == target) return mid;\n        if (arr[mid] < target) left = mid + 1;\n        else right = mid - 1;\n    }\n    return -1;\n}',
    },
    {
      title: 'Two Sum',
      description: 'Given an array of integers and a target sum, find two numbers that add up to the target.',
      language: 'dart',
      difficulty: 'intermediate',
      category: 'algorithms',
      starterCode: 'List<int> twoSum(List<int> nums, int target) {\n    // Your code here\n    return [];\n}',
      hints: ['Use a Map to store seen numbers', 'For each number, check if complement exists', 'Return indices when complement is found'],
      solution: 'List<int> twoSum(List<int> nums, int target) {\n    Map<int, int> map = {};\n    for (int i = 0; i < nums.length; i++) {\n        int complement = target - nums[i];\n        if (map.containsKey(complement)) {\n            return [map[complement]!, i];\n        }\n        map[nums[i]] = i;\n    }\n    return [];\n}',
    },
    {
      title: 'Check Palindrome',
      description: 'Write a function that checks if a string is a palindrome.',
      language: 'dart',
      difficulty: 'intermediate',
      category: 'algorithms',
      starterCode: 'bool isPalindrome(String str) {\n    // Your code here\n    return false;\n}',
      hints: ['Remove spaces and convert to lowercase', 'Compare the string with its reverse'],
      solution: 'bool isPalindrome(String str) {\n    String cleaned = str.toLowerCase().replaceAll(" ", "");\n    return cleaned == cleaned.split("").reversed.join("");\n}',
    },
    {
      title: 'Merge Sorted Arrays',
      description: 'Merge two sorted arrays into one sorted array without using built-in sort methods.',
      language: 'dart',
      difficulty: 'advanced',
      category: 'algorithms',
      starterCode: 'List<int> mergeSortedArrays(List<int> arr1, List<int> arr2) {\n    // Your code here\n    return [];\n}',
      hints: ['Use two pointers, one for each array', 'Compare elements and add smaller one to result', 'Handle remaining elements after one array is exhausted'],
      solution: 'List<int> mergeSortedArrays(List<int> arr1, List<int> arr2) {\n    List<int> result = [];\n    int i = 0, j = 0;\n    while (i < arr1.length && j < arr2.length) {\n        if (arr1[i] < arr2[j]) result.add(arr1[i++]);\n        else result.add(arr2[j++]);\n    }\n    result.addAll(arr1.sublist(i));\n    result.addAll(arr2.sublist(j));\n    return result;\n}',
    },
    {
      title: 'Count Vowels',
      description: 'Write a function that counts the number of vowels (a, e, i, o, u) in a given string.',
      language: 'dart',
      difficulty: 'beginner',
      category: 'algorithms',
      starterCode: 'int countVowels(String str) {\n    // Your code here\n    return 0;\n}',
      hints: ['Convert string to lowercase for case-insensitive matching', 'Count vowels using where'],
      solution: 'int countVowels(String str) {\n    String vowels = "aeiou";\n    return str.toLowerCase().split("").where((c) => vowels.contains(c)).length;\n}',
    },
    // Scala tasks
    {
      title: 'Find Maximum in Array',
      description: 'Write a function that finds and returns the maximum value in an array of integers.',
      language: 'scala',
      difficulty: 'beginner',
      category: 'algorithms',
      starterCode: 'def findMax(arr: Array[Int]): Int = {\n    // Your code here\n    0\n}',
      hints: ['Use max method', 'Or use foldLeft', 'Compare each element'],
      solution: 'def findMax(arr: Array[Int]): Int = {\n    arr.max\n}',
    },
    {
      title: 'Reverse a String',
      description: 'Write a function that takes a string and returns it reversed.',
      language: 'scala',
      difficulty: 'beginner',
      category: 'algorithms',
      starterCode: 'def reverseString(str: String): String = {\n    // Your code here\n    ""\n}',
      hints: ['Use reverse method', 'Or build a new string character by character'],
      solution: 'def reverseString(str: String): String = {\n    str.reverse\n}',
    },
    {
      title: 'Binary Search',
      description: 'Implement binary search to find a target value in a sorted array.',
      language: 'scala',
      difficulty: 'intermediate',
      category: 'algorithms',
      starterCode: 'def binarySearch(arr: Array[Int], target: Int): Int = {\n    // Your code here\n    -1\n}',
      hints: ['Use two pointers: left and right', 'Calculate the middle index', 'Compare target with middle element'],
      solution: 'def binarySearch(arr: Array[Int], target: Int): Int = {\n    var left = 0\n    var right = arr.length - 1\n    while (left <= right) {\n        val mid = left + (right - left) / 2\n        if (arr(mid) == target) return mid\n        if (arr(mid) < target) left = mid + 1\n        else right = mid - 1\n    }\n    -1\n}',
    },
    {
      title: 'Two Sum',
      description: 'Given an array of integers and a target sum, find two numbers that add up to the target.',
      language: 'scala',
      difficulty: 'intermediate',
      category: 'algorithms',
      starterCode: 'def twoSum(nums: Array[Int], target: Int): Array[Int] = {\n    // Your code here\n    Array.empty[Int]\n}',
      hints: ['Use a Map to store seen numbers', 'For each number, check if complement exists', 'Return indices when complement is found'],
      solution: 'def twoSum(nums: Array[Int], target: Int): Array[Int] = {\n    val map = scala.collection.mutable.Map[Int, Int]()\n    for (i <- nums.indices) {\n        val complement = target - nums(i)\n        if (map.contains(complement)) return Array(map(complement), i)\n        map(nums(i)) = i\n    }\n    Array.empty[Int]\n}',
    },
    {
      title: 'Check Palindrome',
      description: 'Write a function that checks if a string is a palindrome.',
      language: 'scala',
      difficulty: 'intermediate',
      category: 'algorithms',
      starterCode: 'def isPalindrome(str: String): Boolean = {\n    // Your code here\n    false\n}',
      hints: ['Remove spaces and convert to lowercase', 'Compare the string with its reverse'],
      solution: 'def isPalindrome(str: String): Boolean = {\n    val cleaned = str.toLowerCase.replaceAll(" ", "")\n    cleaned == cleaned.reverse\n}',
    },
    {
      title: 'Merge Sorted Arrays',
      description: 'Merge two sorted arrays into one sorted array without using built-in sort methods.',
      language: 'scala',
      difficulty: 'advanced',
      category: 'algorithms',
      starterCode: 'def mergeSortedArrays(arr1: Array[Int], arr2: Array[Int]): Array[Int] = {\n    // Your code here\n    Array.empty[Int]\n}',
      hints: ['Use two pointers, one for each array', 'Compare elements and add smaller one to result', 'Handle remaining elements after one array is exhausted'],
      solution: 'def mergeSortedArrays(arr1: Array[Int], arr2: Array[Int]): Array[Int] = {\n    val result = scala.collection.mutable.ArrayBuffer[Int]()\n    var i = 0\n    var j = 0\n    while (i < arr1.length && j < arr2.length) {\n        if (arr1(i) < arr2(j)) {\n            result += arr1(i)\n            i += 1\n        } else {\n            result += arr2(j)\n            j += 1\n        }\n    }\n    result ++= arr1.slice(i, arr1.length)\n    result ++= arr2.slice(j, arr2.length)\n    result.toArray\n}',
    },
    {
      title: 'Count Vowels',
      description: 'Write a function that counts the number of vowels (a, e, i, o, u) in a given string.',
      language: 'scala',
      difficulty: 'beginner',
      category: 'algorithms',
      starterCode: 'def countVowels(str: String): Int = {\n    // Your code here\n    0\n}',
      hints: ['Convert string to lowercase for case-insensitive matching', 'Count vowels using filter'],
      solution: 'def countVowels(str: String): Int = {\n    val vowels = "aeiou"\n    str.toLowerCase.filter(vowels.contains(_)).length\n}',
    },
    // R tasks
    {
      title: 'Find Maximum in Array',
      description: 'Write a function that finds and returns the maximum value in a vector of numbers.',
      language: 'r',
      difficulty: 'beginner',
      category: 'algorithms',
      starterCode: 'find_max <- function(arr) {\n    # Your code here\n}',
      hints: ['Use max() function', 'Or iterate through the vector'],
      solution: 'find_max <- function(arr) {\n    max(arr)\n}',
    },
    {
      title: 'Reverse a Vector',
      description: 'Write a function that reverses a vector of numbers.',
      language: 'r',
      difficulty: 'beginner',
      category: 'algorithms',
      starterCode: 'reverse_vector <- function(arr) {\n    # Your code here\n}',
      hints: ['Use rev() function', 'Or use indexing'],
      solution: 'reverse_vector <- function(arr) {\n    rev(arr)\n}',
    },
    {
      title: 'Binary Search',
      description: 'Implement binary search to find a target value in a sorted vector.',
      language: 'r',
      difficulty: 'intermediate',
      category: 'algorithms',
      starterCode: 'binary_search <- function(arr, target) {\n    # Your code here\n    -1\n}',
      hints: ['Use two pointers: left and right', 'Calculate the middle index', 'Compare target with middle element'],
      solution: 'binary_search <- function(arr, target) {\n    left <- 1\n    right <- length(arr)\n    while (left <= right) {\n        mid <- left + floor((right - left) / 2)\n        if (arr[mid] == target) return(mid)\n        if (arr[mid] < target) left <- mid + 1\n        else right <- mid - 1\n    }\n    -1\n}',
    },
    {
      title: 'Count Elements',
      description: 'Write a function that counts how many elements in a vector are greater than a threshold.',
      language: 'r',
      difficulty: 'intermediate',
      category: 'algorithms',
      starterCode: 'count_greater <- function(arr, threshold) {\n    # Your code here\n    0\n}',
      hints: ['Use sum() with logical comparison', 'Or use length() with which()'],
      solution: 'count_greater <- function(arr, threshold) {\n    sum(arr > threshold)\n}',
    },
    {
      title: 'Merge Sorted Vectors',
      description: 'Merge two sorted vectors into one sorted vector without using built-in sort methods.',
      language: 'r',
      difficulty: 'advanced',
      category: 'algorithms',
      starterCode: 'merge_sorted_vectors <- function(arr1, arr2) {\n    # Your code here\n    c()\n}',
      hints: ['Use two pointers, one for each vector', 'Compare elements and add smaller one to result', 'Handle remaining elements'],
      solution: 'merge_sorted_vectors <- function(arr1, arr2) {\n    result <- c()\n    i <- j <- 1\n    while (i <= length(arr1) && j <= length(arr2)) {\n        if (arr1[i] < arr2[j]) {\n            result <- c(result, arr1[i])\n            i <- i + 1\n        } else {\n            result <- c(result, arr2[j])\n            j <- j + 1\n        }\n    }\n    if (i <= length(arr1)) result <- c(result, arr1[i:length(arr1)])\n    if (j <= length(arr2)) result <- c(result, arr2[j:length(arr2)])\n    result\n}',
    },
    // SQL tasks
    {
      title: 'Find Maximum Value',
      description: 'Write a SQL query to find the maximum value in a column.',
      language: 'sql',
      difficulty: 'beginner',
      category: 'algorithms',
      starterCode: 'SELECT -- Your code here\nFROM table_name;',
      hints: ['Use MAX() aggregate function', 'Specify the column name'],
      solution: 'SELECT MAX(column_name) FROM table_name;',
    },
    {
      title: 'Count Records',
      description: 'Write a SQL query to count the number of records in a table.',
      language: 'sql',
      difficulty: 'beginner',
      category: 'algorithms',
      starterCode: 'SELECT -- Your code here\nFROM table_name;',
      hints: ['Use COUNT() aggregate function', 'Use * to count all rows'],
      solution: 'SELECT COUNT(*) FROM table_name;',
    },
    {
      title: 'Filter Records',
      description: 'Write a SQL query to select records where a column value is greater than a threshold.',
      language: 'sql',
      difficulty: 'intermediate',
      category: 'algorithms',
      starterCode: 'SELECT * FROM table_name\n-- Your code here;',
      hints: ['Use WHERE clause', 'Use comparison operator >'],
      solution: 'SELECT * FROM table_name WHERE column_name > 100;',
    },
    {
      title: 'Join Tables',
      description: 'Write a SQL query to join two tables on a common column.',
      language: 'sql',
      difficulty: 'intermediate',
      category: 'algorithms',
      starterCode: 'SELECT * FROM table1\n-- Your code here\n-- Your code here;',
      hints: ['Use JOIN keyword', 'Specify ON condition with matching columns'],
      solution: 'SELECT * FROM table1 JOIN table2 ON table1.id = table2.id;',
    },
    {
      title: 'Group and Aggregate',
      description: 'Write a SQL query to group records by a column and calculate the average of another column.',
      language: 'sql',
      difficulty: 'advanced',
      category: 'algorithms',
      starterCode: 'SELECT -- Your code here\nFROM table_name\n-- Your code here;',
      hints: ['Use GROUP BY clause', 'Use AVG() aggregate function'],
      solution: 'SELECT category, AVG(price) FROM table_name GROUP BY category;',
    },
    {
      title: 'Subquery',
      description: 'Write a SQL query using a subquery to find records with values above the average.',
      language: 'sql',
      difficulty: 'advanced',
      category: 'algorithms',
      starterCode: 'SELECT * FROM table_name\nWHERE column_name -- Your code here;',
      hints: ['Use WHERE clause with comparison', 'Use subquery with AVG()'],
      solution: 'SELECT * FROM table_name WHERE column_name > (SELECT AVG(column_name) FROM table_name);',
    },
    // Additional tasks for languages that need more coverage
    // Rust - add 1 intermediate task
    {
      title: 'Check Palindrome',
      description: 'Write a function that checks if a string is a palindrome.',
      language: 'rust',
      difficulty: 'intermediate',
      category: 'algorithms',
      starterCode: 'fn is_palindrome(s: &str) -> bool {\n    // Your code here\n    false\n}',
      hints: ['Remove spaces and convert to lowercase', 'Compare the string with its reverse'],
      solution: 'fn is_palindrome(s: &str) -> bool {\n    let cleaned: String = s.to_lowercase().chars().filter(|c| !c.is_whitespace()).collect();\n    cleaned == cleaned.chars().rev().collect::<String>()\n}',
    },
    // Go - add 1 intermediate task
    {
      title: 'Check Palindrome',
      description: 'Write a function that checks if a string is a palindrome.',
      language: 'go',
      difficulty: 'intermediate',
      category: 'algorithms',
      starterCode: 'func isPalindrome(s string) bool {\n    // Your code here\n    return false\n}',
      hints: ['Remove spaces and convert to lowercase', 'Compare characters from both ends'],
      solution: 'func isPalindrome(s string) bool {\n    cleaned := strings.ToLower(strings.ReplaceAll(s, " ", ""))\n    runes := []rune(cleaned)\n    for i, j := 0, len(runes)-1; i < j; i, j = i+1, j-1 {\n        if runes[i] != runes[j] {\n            return false\n        }\n    }\n    return true\n}',
    },
    // Swift - add 1 beginner task (Sum of Array)
    {
      title: 'Sum of Array',
      description: 'Write a function that calculates and returns the sum of all numbers in an array.',
      language: 'swift',
      difficulty: 'beginner',
      category: 'algorithms',
      starterCode: 'func sumArray(_ arr: [Int]) -> Int {\n    // Your code here\n    return 0\n}',
      hints: ['Use reduce method', 'Or iterate through the array', 'Add each element to a running total'],
      solution: 'func sumArray(_ arr: [Int]) -> Int {\n    return arr.reduce(0, +)\n}',
    },
    // Kotlin - add 1 beginner task (Sum of Array)
    {
      title: 'Sum of Array',
      description: 'Write a function that calculates and returns the sum of all numbers in an array.',
      language: 'kotlin',
      difficulty: 'beginner',
      category: 'algorithms',
      starterCode: 'fun sumArray(arr: IntArray): Int {\n    // Your code here\n    return 0\n}',
      hints: ['Use sum() method', 'Or iterate through the array', 'Add each element to a running total'],
      solution: 'fun sumArray(arr: IntArray): Int {\n    return arr.sum()\n}',
    },
    // Dart - add 1 beginner task (Sum of List)
    {
      title: 'Sum of List',
      description: 'Write a function that calculates and returns the sum of all numbers in a list.',
      language: 'dart',
      difficulty: 'beginner',
      category: 'algorithms',
      starterCode: 'int sumList(List<int> arr) {\n    // Your code here\n    return 0;\n}',
      hints: ['Use fold method', 'Or iterate through the list', 'Add each element to a running total'],
      solution: 'int sumList(List<int> arr) {\n    return arr.fold(0, (a, b) => a + b);\n}',
    },
    // Scala - add 1 beginner task (Sum of Array)
    {
      title: 'Sum of Array',
      description: 'Write a function that calculates and returns the sum of all numbers in an array.',
      language: 'scala',
      difficulty: 'beginner',
      category: 'algorithms',
      starterCode: 'def sumArray(arr: Array[Int]): Int = {\n    // Your code here\n    0\n}',
      hints: ['Use sum method', 'Or use foldLeft', 'Add each element to a running total'],
      solution: 'def sumArray(arr: Array[Int]): Int = {\n    arr.sum\n}',
    },
    // R - add 1 beginner and 1 intermediate task
    {
      title: 'Count Vowels in String',
      description: 'Write a function that counts the number of vowels (a, e, i, o, u) in a given string.',
      language: 'r',
      difficulty: 'beginner',
      category: 'algorithms',
      starterCode: 'count_vowels <- function(str) {\n    # Your code here\n    0\n}',
      hints: ['Convert string to lowercase', 'Use strsplit and count vowels'],
      solution: 'count_vowels <- function(str) {\n    vowels <- c("a", "e", "i", "o", "u")\n    chars <- strsplit(tolower(str), "")[[1]]\n    sum(chars %in% vowels)\n}',
    },
    {
      title: 'Two Sum',
      description: 'Given a vector of integers and a target sum, find two numbers that add up to the target.',
      language: 'r',
      difficulty: 'intermediate',
      category: 'algorithms',
      starterCode: 'two_sum <- function(nums, target) {\n    # Your code here\n    c()\n}',
      hints: ['Use a list to store seen numbers', 'For each number, check if complement exists'],
      solution: 'two_sum <- function(nums, target) {\n    seen <- list()\n    for (i in seq_along(nums)) {\n        complement <- target - nums[i]\n        if (!is.null(seen[[as.character(complement)]])) {\n            return(c(seen[[as.character(complement)]], i))\n        }\n        seen[[as.character(nums[i])]] <- i\n    }\n    c()\n}',
    },
  ]

  for (const task of programmingTasks) {
    // Include language in task ID to make it unique across languages
    const taskId = `task-${task.language}-${task.title.toLowerCase().replace(/\s/g, '-')}`
    await prisma.programmingTask.upsert({
      where: { id: taskId },
      update: {
        // Update isActive to true to ensure tasks are visible
        isActive: true,
      },
      create: {
        id: taskId,
        title: task.title,
        description: task.description,
        language: task.language,
        difficulty: task.difficulty,
        category: task.category,
        starterCode: task.starterCode,
        hints: task.hints,
        solution: task.solution,
        isActive: true, // Explicitly set isActive to true
      },
    })
  }

  console.log('Seed data created successfully!')
  console.log(`Created ${assessmentQuestions.length} assessment questions`)
  console.log(`Created ${programmingTasks.length} programming tasks`)
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
